name: Run Announcement Scraper

on:
  schedule:
    - cron: "0 8,20 * * *"   # τρέχει κάθε μέρα στις 08:00 και 20:00 UTC
  workflow_dispatch:          # μπορείς να το τρέξεις και χειροκίνητα

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Run scraper
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ANNOUNCEMENTS_URL: ${{ secrets.ANNOUNCEMENTS_URL }}
        run: |
          python python/main.py

