name: Run Announcement Scraper

on:
  schedule:
    - cron: "0 8,20 * * *"   # τρέχει κάθε μέρα στις 08:00 και 20:00 UTC
  workflow_dispatch:          # να μπορείς να το τρέξεις χειροκίνητα

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ANNOUNCEMENTS_URL: ${{ secrets.ANNOUNCEMENTS_URL }}
        run: |
          python python/main.py

      - name: Commit updated file
        if: success()  # θα γίνει μόνο αν το προηγούμενο βήμα ήταν επιτυχές
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add python/anakoinwseis.txt
          git commit -m "Update announcements file" || echo "No changes to commit"
          git push
